baseURL = 'https://sujee.github.io/ai-events-recap/'
languageCode = 'en-us'
title = 'AI Events Recap'
theme = 'ink-free-sujee'
canonifyURLs = true

# Google Analytics - replace with your actual GA4 measurement ID
googleAnalytics = 'G-HGLK33NHNM'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  tag = "tags"
  genre = "genres"
  category = "categories"

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 10

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 30

# Markdown configuration for external links
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

# Ink Free theme configuration
[params]
  author = "Your Name"
  description = "A minimal Hugo blog"
  wpm = 200
  maxTags = 5

# Privacy configuration for GDPR compliance
[privacy]
  [privacy.googleAnalytics]
    respectDoNotTrack = true
    anonymizeIP = true
    useSessionStorage = false