baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'AI Events Recap'
theme = 'ink-free-sujee'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  tag = "tags"
  genre = "genres"
  category = "categories"

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 10

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 30

# Ink Free theme configuration
[params]
  author = "Your Name"
  description = "A minimal Hugo blog"
  wpm = 200
  maxTags = 5